/* Conroy's Training App - auto-split for reliable GitHub deploy */
// ========== DATA & I18N ==========
    const i18n = {
      ko: {
        login_title: "직원 로그인", login_desc: "아이디와 비밀번호를 입력하세요",
        username_ph: "아이디", password_ph: "비밀번호", login_btn: "로그인",
        login_error: "아이디 또는 비밀번호가 올바르지 않습니다.",
        today_routine: "오늘의 루틴", customer: "손님 응대", phone: "전화 받기",
        messages: "Messages 확인", back_routine: "루틴으로", day_end_summary: "하루 마무리",
        view_summary: "오늘 요약 보기", customer_title: "손님 응대 가이드",
        customer_priority: "고객 우선! 하던 일을 멈추고 즉시 인사하세요.",
        greeting: "인사말", greeting_script: '"Welcome! How can I help you today?" / "안녕하세요! 무엇을 도와드릴까요?"',
        needs: "니즈 파악", needs_script: '"Who\'s going to receive the flowers?" (받는 분이 누구신가요?)',
        color_guide: "색상 추천", color_romance: "Romance → Red / Hot Pink",
        color_family: "Family → Light Pink", color_friends: "Friends / Get Well → Bright Colors",
        color_sympathy: "Sympathy → White / Soft Pastels", size_guide: "사이즈 추천 스크립트",
        size_small: "작은 화병 어레인지먼트를 추천드려요. 책상이나 사이드 테이블에 딱 좋고, 신선한 가든 플라워로 구성됩니다. $40–60.",
        size_medium_rec: "가장 기본 추천", size_medium: "미디엄 화병 어레인지먼트를 추천드려요. 책상이나 사이드 테이블에 완벽하고, 신선한 가든 플라워로 구성됩니다. $60–80.",
        size_large: "특별한 날에는 라지 화병 어레인지먼트를 추천드려요. 테이블 센터피스나 입구에 잘 어울리고, 프리미엄 신선한 꽃으로 만들어 깊은 인상을 남깁니다. $100부터.",
        phone_title: "전화 응대", phone_priority: "손님이 매장에 있으면 먼저 손님을 도와주세요.",
        phone_greeting: "인사말", phone_script: '"Thank you for calling Conroy\'s Flowers. How may I help you?"',
        phone_hold: "홀드할 때", phone_hold_script: '"Thank you for calling Conroy\'s. May I place you on a brief hold?"',
        messages_title: "Messages / In Wire 확인",
        messages_warn: "Wire-In 주문이 들어오면 Messages와 In Wire 카운터가 올라갑니다. 수시로 확인하세요!",
        msg_step1: "Messages 열기 → 내용 확인 (받는 분, 주소, 배송일, 특별지시)",
        msg_step2: "Mark Read 클릭", msg_step3: "In Wire로 이동 → 주문 검토 후 Accept",
        msg_step4: "Accept 후 To Be Designed로 이동 + SuperTicket 자동 출력 (Register 1)",
        msg_reject: "Reject는 매니저 승인 없이 절대 누르지 마세요.",
        superticket_caption: "SuperTicket 예시 – 디자인 시작 전 반드시 출력된 티켓을 확인하세요.",
        checked_back: "확인 완료 & 루틴으로", search_title: "질문하기 / 검색",
        search_ph: "예: SuperTicket, CardIsle, 배달...", search_btn: "검색",
        quick_topics: "자주 찾는 주제", training_title: "트레이닝 & 가이드",
        att_check: "첨부물 확인 · 부착 절차", bms_flow: "BMS 주문 처리 흐름",
        delivery_guide: "배달 가이드", golden_rules: "Golden Rules", decision_helper: "모르겠을 때 도우미",
        feedback_title: "피드백 / 업그레이드", feedback_ph: "앱에서 부족한 점이나 자주 헷갈리는 질문을 적어주세요",
        save_feedback: "저장하기", logout: "로그아웃",
        nav_home: "루틴", nav_customer: "손님", nav_msg: "Messages", nav_search: "검색", nav_more: "더보기"
      },
      en: {
        login_title: "Employee Login", login_desc: "Enter your ID and password",
        username_ph: "Username", password_ph: "Password", login_btn: "Log in",
        login_error: "Invalid username or password.",
        today_routine: "Today's Routine", customer: "Customer", phone: "Phone",
        messages: "Check Messages", back_routine: "Back to Routine", day_end_summary: "End of Day",
        view_summary: "View Today's Summary", customer_title: "Customer Service Guide",
        customer_priority: "Customer first! Stop what you're doing and greet immediately.",
        greeting: "Greeting", greeting_script: '"Welcome! How can I help you today?"',
        needs: "Understanding Needs", needs_script: '"Who\'s going to receive the flowers?"',
        color_guide: "Color Recommendations", color_romance: "Romance → Red / Hot Pink",
        color_family: "Family → Light Pink", color_friends: "Friends / Get Well → Bright Colors",
        color_sympathy: "Sympathy → White / Soft Pastels", size_guide: "Size Recommendation Scripts",
        size_small: "I'd recommend one of our small vase arrangements, perfect for a desk or side table, filled with fresh garden flowers. $40–60.",
        size_medium_rec: "Standard recommendation", size_medium: "I'd recommend a medium vase arrangement, perfect for a desk or end table, filled with fresh garden flowers. $60–80.",
        size_large: "For an occasion this special, I'd recommend one of our large vase arrangements. Perfect as a centerpiece. Starting from $100.",
        phone_title: "Phone Handling", phone_priority: "If a customer is in the store, help them first.",
        phone_greeting: "Greeting", phone_script: '"Thank you for calling Conroy\'s Flowers. How may I help you?"',
        phone_hold: "Putting on Hold", phone_hold_script: '"Thank you for calling Conroy\'s. May I place you on a brief hold?"',
        messages_title: "Messages / In Wire Check",
        messages_warn: "When a Wire-In order arrives, Messages and In Wire counters increase. Check frequently!",
        msg_step1: "Open Messages → Review details (recipient, address, delivery date, special instructions)",
        msg_step2: "Click Mark Read", msg_step3: "Go to In Wire → Review and click Accept",
        msg_step4: "After Accept → moves to To Be Designed + SuperTicket auto-prints (Register 1)",
        msg_reject: "Never click Reject without manager approval.",
        superticket_caption: "SuperTicket example – Always check the printed ticket before designing.",
        checked_back: "Checked & Back to Routine", search_title: "Ask / Search",
        search_ph: "e.g. SuperTicket, CardIsle, delivery...", search_btn: "Search",
        quick_topics: "Quick Topics", training_title: "Training & Guides",
        att_check: "Attachment Verification Process", bms_flow: "BMS Order Flow",
        delivery_guide: "Delivery Guide", golden_rules: "Golden Rules", decision_helper: "If Unsure Helper",
        feedback_title: "Feedback / Upgrade", feedback_ph: "Note anything missing or confusing questions",
        save_feedback: "Save", logout: "Log out",
        nav_home: "Routine", nav_customer: "Customer", nav_msg: "Messages", nav_search: "Search", nav_more: "More"
      },
      ja: {
        login_title: "従業員ログイン", login_desc: "IDとパスワードを入力してください",
        username_ph: "ユーザーID", password_ph: "パスワード", login_btn: "ログイン",
        login_error: "IDまたはパスワードが正しくありません。",
        today_routine: "今日のルーティン", customer: "来客対応", phone: "電話対応",
        messages: "Messages確認", back_routine: "ルーティンに戻る", day_end_summary: "一日のまとめ",
        view_summary: "今日のサマリーを見る", customer_title: "来客対応ガイド",
        customer_priority: "お客様優先！作業を止めてすぐに挨拶してください。",
        greeting: "挨拶", greeting_script: '"Welcome! How can I help you today?"',
        needs: "ニーズ把握", needs_script: '"Who\'s going to receive the flowers?"',
        color_guide: "色の推奨", color_romance: "Romance → Red / Hot Pink",
        color_family: "Family → Light Pink", color_friends: "Friends / Get Well → Bright Colors",
        color_sympathy: "Sympathy → White / Soft Pastels", size_guide: "サイズ推奨スクリプト",
        size_small: "小さな花瓶アレンジメントをおすすめします。デスクやサイドテーブルに最適、$40–60。",
        size_medium_rec: "標準推奨", size_medium: "ミディアム花瓶アレンジメントをおすすめします。$60–80。",
        size_large: "特別な機会にはラージをおすすめします。$100から。",
        phone_title: "電話対応", phone_priority: "店内にお客様がいる場合は先にお客様を優先してください。",
        phone_greeting: "挨拶", phone_script: '"Thank you for calling Conroy\'s Flowers. How may I help you?"',
        phone_hold: "保留する時", phone_hold_script: '"Thank you for calling Conroy\'s. May I place you on a brief hold?"',
        messages_title: "Messages / In Wire 確認",
        messages_warn: "Wire-In注文が入るとMessagesとIn Wireのカウンターが増えます。頻繁に確認してください！",
        msg_step1: "Messagesを開く → 内容確認", msg_step2: "Mark Readをクリック",
        msg_step3: "In Wireへ → 確認後Accept", msg_step4: "Accept後 To Be Designedへ + SuperTicket自動印刷",
        msg_reject: "マネージャーの承認なしにRejectを押さないでください。",
        superticket_caption: "SuperTicket例 – デザイン前に必ず印刷されたチケットを確認。",
        checked_back: "確認完了 & ルーティンに戻る", search_title: "質問 / 検索",
        search_ph: "例: SuperTicket, CardIsle, 配達...", search_btn: "検索",
        quick_topics: "よく探すトピック", training_title: "トレーニング & ガイド",
        att_check: "添付物確認・取り付け手順", bms_flow: "BMS注文処理フロー",
        delivery_guide: "配達ガイド", golden_rules: "Golden Rules", decision_helper: "迷った時のヘルパー",
        feedback_title: "フィードバック", feedback_ph: "不足している点やよく迷う質問を書いてください",
        save_feedback: "保存", logout: "ログアウト",
        nav_home: "ルーティン", nav_customer: "来客", nav_msg: "Messages", nav_search: "検索", nav_more: "もっと"
      },
      es: {
        login_title: "Inicio de sesión", login_desc: "Ingrese su ID y contraseña",
        username_ph: "Usuario", password_ph: "Contraseña", login_btn: "Iniciar sesión",
        login_error: "Usuario o contraseña incorrectos.",
        today_routine: "Rutina de hoy", customer: "Cliente", phone: "Teléfono",
        messages: "Revisar Messages", back_routine: "Volver a rutina", day_end_summary: "Fin del día",
        view_summary: "Ver resumen de hoy", customer_title: "Guía de atención al cliente",
        customer_priority: "¡Cliente primero! Detenga lo que está haciendo y salude de inmediato.",
        greeting: "Saludo", greeting_script: '"Welcome! How can I help you today?"',
        needs: "Necesidades", needs_script: '"Who\'s going to receive the flowers?"',
        color_guide: "Recomendación de colores", color_romance: "Romance → Red / Hot Pink",
        color_family: "Family → Light Pink", color_friends: "Friends / Get Well → Bright Colors",
        color_sympathy: "Sympathy → White / Soft Pastels", size_guide: "Scripts de tamaño",
        size_small: "Recomiendo un arreglo pequeño en jarrón, perfecto para escritorio. $40–60.",
        size_medium_rec: "Recomendación estándar", size_medium: "Recomiendo un arreglo mediano. $60–80.",
        size_large: "Para una ocasión especial, recomiendo un arreglo grande. Desde $100.",
        phone_title: "Atención telefónica", phone_priority: "Si hay un cliente en la tienda, ayúdelo primero.",
        phone_greeting: "Saludo", phone_script: '"Thank you for calling Conroy\'s Flowers. How may I help you?"',
        phone_hold: "Poner en espera", phone_hold_script: '"Thank you for calling Conroy\'s. May I place you on a brief hold?"',
        messages_title: "Messages / In Wire",
        messages_warn: "Cuando llega un pedido Wire-In, aumentan los contadores. ¡Revise con frecuencia!",
        msg_step1: "Abrir Messages → Revisar detalles", msg_step2: "Clic en Mark Read",
        msg_step3: "Ir a In Wire → Revisar y Accept", msg_step4: "Después de Accept → To Be Designed + SuperTicket se imprime",
        msg_reject: "Nunca haga clic en Reject sin aprobación del gerente.",
        superticket_caption: "Ejemplo de SuperTicket – Siempre verifique el ticket impreso antes de diseñar.",
        checked_back: "Revisado y volver a rutina", search_title: "Preguntar / Buscar",
        search_ph: "ej. SuperTicket, CardIsle, entrega...", search_btn: "Buscar",
        quick_topics: "Temas frecuentes", training_title: "Capacitación y guías",
        att_check: "Proceso de verificación de adjuntos", bms_flow: "Flujo de pedidos BMS",
        delivery_guide: "Guía de entrega", golden_rules: "Golden Rules", decision_helper: "Si no está seguro",
        feedback_title: "Comentarios", feedback_ph: "Anote lo que falta o preguntas confusas",
        save_feedback: "Guardar", logout: "Cerrar sesión",
        nav_home: "Rutina", nav_customer: "Cliente", nav_msg: "Messages", nav_search: "Buscar", nav_more: "Más"
      }
    };

    // Routine stamps definition
    const routineTasks = [
      { id: 'funeral_check', title: {ko:'Funeral / 긴급 주문 확인', en:'Funeral / Urgent Order Check', ja:'Funeral / 緊急注文確認', es:'Funeral / Pedido urgente'}, desc: {ko:'개별 배송 – Messages/In Wire에서 Funeral 주문을 가장 먼저 확인', en:'Individual delivery – Check Funeral orders first in Messages/In Wire', ja:'個別配達 – Messages/In WireでFuneralを最優先確認', es:'Entrega individual – Revisar primero Funeral en Messages/In Wire'} },
      { id: 'open_shop', title: {ko:'가게 문/조명 확인', en:'Open gate/lights if needed', ja:'門・照明確認', es:'Abrir puerta/luces'}, desc: {ko:'필요시 외부 게이트/조명 켜기', en:'Open outside gate/fence, turn on lights', ja:'必要に応じて門と照明', es:'Abrir portón y luces si es necesario'} },
      { id: 'start_day', title: {ko:'Start Day (캐시 카운트)', en:'Start Day (Cash Count)', ja:'Start Day（現金確認）', es:'Start Day (Conteo de efectivo)'}, desc: {ko:'$200.00 맞추고 금액+사진 저장', en:'Count to $200.00, enter amount + photo', ja:'$200.00を確認し金額＋写真', es:'Contar $200.00, ingresar monto + foto'}, special: 'startday' },
      { id: 'cooler_vase', title: {ko:'쿨러 화병 점검', en:'Cooler Vase Check', ja:'クーラー花瓶チェック', es:'Revisión de jarrones'}, desc: {ko:'물 갈기, 손상된 꽃 제거, 줄기 재절단', en:'Check water, remove damaged flowers, re-cut stems', ja:'水替え・傷んだ花除去', es:'Revisar agua, quitar flores dañadas'} },
      { id: 'cooler_loose', title: {ko:'루스 플라워 점검', en:'Loose Flower Buckets', ja:'切り花バケツ確認', es:'Cubos de flores sueltas'}, desc: {ko:'물 보충, 손상 꽃 제거, 색상별 정리', en:'Refill water, remove damaged, organize by color', ja:'水補充・整理', es:'Rellenar agua y organizar'} },
      { id: 'messages_check', title: {ko:'Messages / In Wire 확인', en:'Messages / In Wire Check', ja:'Messages確認', es:'Revisar Messages'}, desc: {ko:'수시로 확인 – 빠른 버튼 사용 가능', en:'Check frequently – use quick button', ja:'頻繁に確認', es:'Revisar con frecuencia'} },
      { id: 'monitor_orders', title: {ko:'주문 모니터링', en:'Monitor Incoming Orders', ja:'注文モニタリング', es:'Monitorear pedidos'}, desc: {ko:'Due Time 우선순위로 처리', en:'Prioritize by Due Time', ja:'Due Time優先', es:'Priorizar por Due Time'} },
      { id: 'attachments', title: {ko:'첨부물 확인 습관화', en:'Attachment Verification Habit', ja:'添付物確認', es:'Verificar adjuntos'}, desc: {ko:'풍선·초콜릿·인형·CardIsle 확인', en:'Balloons, chocolates, plush, CardIsle', ja:'バルーン・チョコ・ぬいぐるみ・カード', es:'Globos, chocolates, peluche, CardIsle'} },
      { id: 'end_day', title: {ko:'End Day (마감)', en:'End Day (Close)', ja:'End Day（締め）', es:'End Day (Cierre)'}, desc: {ko:'$200 남기고 금액+사진 저장, 봉투 처리', en:'Leave $200, amount + photo, deposit envelope', ja:'$200残し金額＋写真', es:'Dejar $200, monto + foto'}, special: 'endday' }
    ];

    // Knowledge base for search
    const knowledge = [
      { keys: ['superticket', '슈퍼티켓', 'ticket', '티켓'], title: {ko:'SuperTicket', en:'SuperTicket', ja:'SuperTicket', es:'SuperTicket'},
        body: {ko:'SuperTicket은 주문 수락 후 자동 출력되는 생산 문서입니다. Recipient Info, White Sheet, Small Ticket으로 구성. 디자인 시작 전 반드시 출력된 티켓을 확인하세요. Register 1에서만 Auto-Print됩니다.', en:'SuperTicket is the primary production document printed after Accept. Contains Recipient Info, White Sheet, Small Ticket. Never design without a printed ticket. Only Register 1 has Auto-Print.', ja:'SuperTicketはAccept後に自動印刷される生産文書です。デザイン前に必ず確認。', es:'SuperTicket es el documento de producción principal. Nunca diseñe sin el ticket impreso.'} },
      { keys: ['attachment', '첨부', '첨부물', 'balloon', 'chocolate', 'plush', 'cardisle'], title: {ko:'첨부물 확인 · 부착 절차', en:'Attachment Verification Process', ja:'添付物確認・取り付け手順', es:'Proceso de verificación de adjuntos'},
        body: {ko:'1. White Sheet Product Detail 확인 → 2. 필요한 첨부물 파악 (풍선/초콜릿/인형/CardIsle) → 3. 준비 → 4. 부착 → 5. 최종 확인 → 6. White Sheet 제거 → 7. Set As Awaiting Delivery. CardIsle은 PickupCodeID로 cardisle.com에서 인쇄 후 뒷면 코드 확인.', en:'1. Check White Sheet Product Detail → 2. Identify required attachments (balloon/chocolate/plush/CardIsle) → 3. Prepare → 4. Attach → 5. Final check → 6. Remove White Sheet → 7. Set As Awaiting Delivery. CardIsle: print with PickupCodeID on cardisle.com and match back code.', ja:'1. White Sheet Product Detail確認 → 2. 必要な添付物を把握 → 3. 準備 → 4. 取り付け → 5. 最終確認 → 6. White Sheetを外す → 7. Set As Awaiting Delivery。', es:'1. Revisar Product Detail → 2. Identificar adjuntos → 3. Preparar → 4. Colocar → 5. Verificación final → 6. Quitar White Sheet → 7. Set As Awaiting Delivery.'} },
      { keys: ['cardisle', '카드', 'greeting card', 'pickupcode'], title: {ko:'CardIsle 인사카드', en:'CardIsle Greeting Card', ja:'CardIsleカード', es:'Tarjeta CardIsle'},
        body: {ko:'PickupCodeID는 White Sheet 하단 Special Instructions 또는 BMS에서 확인. cardisle.com 접속 → 코드 입력 → Preview → Print. 인쇄 후 카드 뒷면 코드와 일치하는지 확인 후 부착. 1800Flowers $5.99 / 매장 $6.99', en:'Find PickupCodeID in Special Instructions or BMS. Go to cardisle.com → enter code → Preview → Print. Match code on back of card before attaching.', ja:'PickupCodeIDを確認しcardisle.comで印刷。コード一致を確認。', es:'Busque PickupCodeID, imprima en cardisle.com y verifique el código.'} },
      { keys: ['delivery', '배달', 'walmart', 'uber', 'trip'], title: {ko:'배달 트립 생성', en:'Create Delivery Trip', ja:'配達トリップ', es:'Crear viaje de entrega'},
        body: {ko:'일반 배달: Provider = Walmart GoLocal, 3Hr Window, 가장 빠른 창 선택 후 Set Trip as Out for Delivery. 장례(Funeral): Provider = Uber, ASAP. 드라이버 도착 시 운반 방법 설명 + 확인 사진 요청.', en:'Standard: Walmart GoLocal + 3Hr Window, earliest available. Funeral: Uber + ASAP. Instruct driver on setup and ask for confirmation photo.', ja:'通常: Walmart GoLocal 3時間。葬儀: Uber ASAP。', es:'Estándar: Walmart GoLocal 3h. Funeral: Uber ASAP.'} },
      { keys: ['startday', 'start day', '캐시', 'cash', '200'], title: {ko:'Start Day', en:'Start Day', ja:'Start Day', es:'Start Day'},
        body: {ko:'Home → Start Day / End Day. Open Cash Drawer (비번 123456). 권종별 수량 입력 (금액 아님). Start Day Amount = 항상 $200.00. 안 맞으면 사진 찍어서 (213) 610-1004로 보내고 조정 없이 진행.', en:'Enter quantity of each denomination (not dollar amount). Must equal $200.00. If not, take photo, send to (213) 610-1004, continue without adjustment.', ja:'各金種の数量を入力。必ず$200.00。合わない場合は写真を送信。', es:'Ingrese cantidad de cada denominación. Debe ser $200.00. Si no, tome foto y envíe.'} },
      { keys: ['endday', 'end day', '마감'], title: {ko:'End Day', en:'End Day', ja:'End Day', es:'End Day'},
        body: {ko:'정확히 $200.00을 드로어에 남김. Summary Receipt 출력 → 초과 현금을 봉투에 넣고 날짜·이름·Cash Sales·Drop 적어서 봉인 → 금고 보관 → End Register Session.', en:'Leave exactly $200.00 in drawer. Print Summary Receipt, put excess cash in deposit envelope with Date, Name, Cash Sales, Drop → safe → End Register Session.', ja:'$200.00を残し、超過分を封筒に入れて金庫へ。', es:'Deje exactamente $200.00. Sobre de depósito al seguro.'} },
      { keys: ['funeral', '장례', 'uber'], title: {ko:'Funeral 배달', en:'Funeral Delivery', ja:'葬儀配達', es:'Entrega de funeral'},
        body: {ko:'시간 민감. Provider: Uber, ASAP로 요청. 드라이버 도착 시 운반 방법 설명하고, 배치 후 확인 사진 찍도록 지시.', en:'Time-sensitive. Use Uber + ASAP. Explain transport to driver and request confirmation photo after setup.', ja:'Uber ASAP。ドライバーに説明と写真を依頼。', es:'Usar Uber ASAP. Explicar al conductor y pedir foto.'} },
      { keys: ['wireout', 'wire-out', 'wire out'], title: {ko:'Wire-Out 주문', en:'Wire-Out Order', ja:'Wire-Out注文', es:'Pedido Wire-Out'},
        body: {ko:'다른 꽃집이 이행. 고객은 1800Flowers 제품 가이드에서 선택. 할인 불가. 전송 전 반드시 받는 꽃집에 전화해서 제품·배송일·배송비 확인 후 BloomLink로 전송.', en:'Another florist fulfills. Customer selects from 1800Flowers guide. No discounts. Always call receiving florist to confirm availability, date, fee before sending via BloomLink.', ja:'受取花屋に電話確認後に送信。割引不可。', es:'Llame al florista receptor antes de enviar. Sin descuentos.'} },
      { keys: ['golden', 'rule', '규칙'], title: {ko:'Golden Rules', en:'Golden Rules', ja:'Golden Rules', es:'Golden Rules'},
        body: {ko:'1. Due Time 기준 우선순위. 2. 인쇄된 Design Ticket 없이 디자인 시작 금지. 3. 모든 작업 끝나기 전 Complete 금지. 4. 배송일 변경 전 Delivery Attempted 메시지 전송. 5. 확신이 없으면 매니저에게 먼저 문의.', en:'1. Prioritize by Due Time. 2. Never design without printed ticket. 3. Do not complete until all work finished. 4. Send Delivery Attempted before changing date. 5. If unsure, contact manager first.', ja:'Due Time優先。チケットなしデザイン禁止。不明な時はマネージャーに。', es:'Priorizar por Due Time. Nunca diseñar sin ticket. Si duda, pregunte al gerente.'} },
      { keys: ['reject', '거절'], title: {ko:'주문 Reject', en:'Order Reject', ja:'Reject', es:'Rechazar pedido'},
        body: {ko:'매니저 승인 없이 Reject를 누르지 마세요. 반드시 매니저에게 먼저 확인하세요.', en:'Never click Reject without management approval.', ja:'マネージャー承認なしにRejectしない。', es:'Nunca rechace sin aprobación del gerente.'} }
    ];

    